import "./Category.scss";
import React from "react";

const Category = () => {
  return (
    <div className="category">
      <div>
        <h3>Action</h3>
        <img
          className="action"
          src="https://www.programme-tv.net/imgre/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Ftel.2F2019.2F04.2F19.2F3b0b6d2b-1cb3-4e9d-aa17-3c7774bd4411.2Ejpeg/1200x600/crop-from/top/quality/80/netflix-notre-top-10-des-meilleurs-films-d-action-disponibles-sur-la-plateforme-svod.jpg"
          alt="action"
        />
      </div>
      <div>
        <h3>Comedy</h3>
        <img
          className="comedy"
          src="https://i0.wp.com/cinedweller.com/wp-content/uploads/2020/05/le-diner-de-cons-cinedweller.jpg?resize=1040%2C550&ssl=1"
          alt="comedy"
        />
      </div>
      <div>
        <h3>Drama</h3>
        <img
          className="drama"
          src="https://fr.web.img4.acsta.net/medias/nmedia/18/66/15/78/19254683.jpg"
          alt="drama"
        />
      </div>
      <div>
        <h3>Science fiction</h3>
        <img
          className="sci-fi"
          src="https://ledrenche.ouest-france.fr/wp-content/uploads/interstellar-the-movie-475.jpg"
          alt="sci-fi"
        />
      </div>
      <div>
        <h3>Fantastic</h3>
        <img
          className="fanstastic"
          src="https://cinevallee.fr/wp-content/uploads/2019/06/Affiche-site.jpg"
          alt="fantactic"
        />
      </div>
      <div>
        <h3>Horror</h3>
        <img
          className="horror"
          src="https://www.urban-fusions.fr/wp-content/uploads/2021/06/ca-le-realisateur-evoque-une-version-longue-avec-les-deux-filmsm-1.jpg"
          alt="horror"
        />
      </div>
      <div>
        <h3>Animated</h3>
        <img
          className="animated"
          src="https://commstudentako.files.wordpress.com/2015/08/wall-e.jpg"
          alt="animated"
        />
      </div>
      <div>
        <h3>Documentary</h3>
        <img
          className="documentary"
          src="https://images.radio-canada.ca/q_auto,w_960/v1/ici-info/16x9/hold-up-documentaire.jpg"
          alt="documentary"
        />
      </div>
      <div>
        <h3>Thriller</h3>
        <img
          className="thriller"
          src="https://static.fnac-static.com/multimedia/FR/Images_Produits/FR/fnac.com/Visual_Principal_340/8/2/5/0886978043528/tsp20120921091226/Black-swan.jpg"
          alt="thriller"
        />
      </div>
      <div>
        <h3>Romance</h3>
        <img
          className="romance"
          src="https://static1.refinery29.com/bin/entry/163/x,80/1166113/1.jpg"
          alt="romance"
        />
      </div>
      <div>
        <h3>Biopic</h3>
        <img
          className="biopic"
          src="https://www.ballecourbe.ca/wp-content/uploads/2020/11/film-Ali.jpg"
          alt="biopic"
        />
      </div>
      <div>
        <h3>Musical</h3>
        <img
          className="musical"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlhGhgATiYQiSGVZ4XEg4HPgZW0n3pd0fAS3FtwvnTqcFR4yGuizi2kB5HDBfLovESgxc&usqp=CAU"
          alt="musical"
        />
      </div>
    </div>
  );
};

export default Category;
